/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptionsIndexOriginalRouteImport } from './routes/options/index-original'
import { Route as OptionsIndexOption6RouteImport } from './routes/options/index-option-6'
import { Route as OptionsIndexOption5bRouteImport } from './routes/options/index-option-5b'
import { Route as OptionsIndexOption5RouteImport } from './routes/options/index-option-5'
import { Route as OptionsIndexOption4RouteImport } from './routes/options/index-option-4'
import { Route as OptionsIndexOption3RouteImport } from './routes/options/index-option-3'
import { Route as OptionsIndexOption2RouteImport } from './routes/options/index-option-2'
import { Route as OptionsIndexOption1bRouteImport } from './routes/options/index-option-1b'
import { Route as OptionsIndexOption1RouteImport } from './routes/options/index-option-1'
import { Route as CountryCountryIdRouteImport } from './routes/country.$countryId'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminFeaturedRouteImport } from './routes/_authenticated/admin/featured'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin/countries'
import { Route as AuthenticatedAdminColoursRouteImport } from './routes/_authenticated/admin/colours'
import { Route as CountryCountryIdCityCityIdRouteImport } from './routes/country.$countryId.city.$cityId'
import { Route as AuthenticatedAdminCountryCountryIdRouteImport } from './routes/_authenticated/admin/country.$countryId'
import { Route as AuthenticatedAdminCountryCountryIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/index'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/index'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/place.$placeId'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/place.$placeId/index'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOriginalRoute = OptionsIndexOriginalRouteImport.update({
  id: '/options/index-original',
  path: '/options/index-original',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption6Route = OptionsIndexOption6RouteImport.update({
  id: '/options/index-option-6',
  path: '/options/index-option-6',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption5bRoute = OptionsIndexOption5bRouteImport.update({
  id: '/options/index-option-5b',
  path: '/options/index-option-5b',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption5Route = OptionsIndexOption5RouteImport.update({
  id: '/options/index-option-5',
  path: '/options/index-option-5',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption4Route = OptionsIndexOption4RouteImport.update({
  id: '/options/index-option-4',
  path: '/options/index-option-4',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption3Route = OptionsIndexOption3RouteImport.update({
  id: '/options/index-option-3',
  path: '/options/index-option-3',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption2Route = OptionsIndexOption2RouteImport.update({
  id: '/options/index-option-2',
  path: '/options/index-option-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption1bRoute = OptionsIndexOption1bRouteImport.update({
  id: '/options/index-option-1b',
  path: '/options/index-option-1b',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsIndexOption1Route = OptionsIndexOption1RouteImport.update({
  id: '/options/index-option-1',
  path: '/options/index-option-1',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCountryIdRoute = CountryCountryIdRouteImport.update({
  id: '/country/$countryId',
  path: '/country/$countryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFeaturedRoute =
  AuthenticatedAdminFeaturedRouteImport.update({
    id: '/featured',
    path: '/featured',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColoursRoute =
  AuthenticatedAdminColoursRouteImport.update({
    id: '/colours',
    path: '/colours',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const CountryCountryIdCityCityIdRoute =
  CountryCountryIdCityCityIdRouteImport.update({
    id: '/city/$cityId',
    path: '/city/$cityId',
    getParentRoute: () => CountryCountryIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdRoute =
  AuthenticatedAdminCountryCountryIdRouteImport.update({
    id: '/country/$countryId',
    path: '/country/$countryId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdIndexRoute =
  AuthenticatedAdminCountryCountryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdRouteImport.update({
    id: '/city/$cityId',
    path: '/city/$cityId',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdCityCityIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport.update({
    id: '/place/$placeId',
    path: '/place/$placeId',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdCityCityIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/country/$countryId': typeof CountryCountryIdRouteWithChildren
  '/options/index-option-1': typeof OptionsIndexOption1Route
  '/options/index-option-1b': typeof OptionsIndexOption1bRoute
  '/options/index-option-2': typeof OptionsIndexOption2Route
  '/options/index-option-3': typeof OptionsIndexOption3Route
  '/options/index-option-4': typeof OptionsIndexOption4Route
  '/options/index-option-5': typeof OptionsIndexOption5Route
  '/options/index-option-5b': typeof OptionsIndexOption5bRoute
  '/options/index-option-6': typeof OptionsIndexOption6Route
  '/options/index-original': typeof OptionsIndexOriginalRoute
  '/admin/colours': typeof AuthenticatedAdminColoursRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
  '/country/$countryId/city/$cityId': typeof CountryCountryIdCityCityIdRoute
  '/admin/country/$countryId/': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
  '/admin/country/$countryId/city/$cityId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
  '/admin/country/$countryId/city/$cityId/place/$placeId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/country/$countryId': typeof CountryCountryIdRouteWithChildren
  '/options/index-option-1': typeof OptionsIndexOption1Route
  '/options/index-option-1b': typeof OptionsIndexOption1bRoute
  '/options/index-option-2': typeof OptionsIndexOption2Route
  '/options/index-option-3': typeof OptionsIndexOption3Route
  '/options/index-option-4': typeof OptionsIndexOption4Route
  '/options/index-option-5': typeof OptionsIndexOption5Route
  '/options/index-option-5b': typeof OptionsIndexOption5bRoute
  '/options/index-option-6': typeof OptionsIndexOption6Route
  '/options/index-original': typeof OptionsIndexOriginalRoute
  '/admin/colours': typeof AuthenticatedAdminColoursRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/country/$countryId/city/$cityId': typeof CountryCountryIdCityCityIdRoute
  '/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/country/$countryId': typeof CountryCountryIdRouteWithChildren
  '/options/index-option-1': typeof OptionsIndexOption1Route
  '/options/index-option-1b': typeof OptionsIndexOption1bRoute
  '/options/index-option-2': typeof OptionsIndexOption2Route
  '/options/index-option-3': typeof OptionsIndexOption3Route
  '/options/index-option-4': typeof OptionsIndexOption4Route
  '/options/index-option-5': typeof OptionsIndexOption5Route
  '/options/index-option-5b': typeof OptionsIndexOption5bRoute
  '/options/index-option-6': typeof OptionsIndexOption6Route
  '/options/index-original': typeof OptionsIndexOriginalRoute
  '/_authenticated/admin/colours': typeof AuthenticatedAdminColoursRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
  '/country/$countryId/city/$cityId': typeof CountryCountryIdCityCityIdRoute
  '/_authenticated/admin/country/$countryId/': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/_authenticated/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
  '/_authenticated/admin/country/$countryId/city/$cityId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
  '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/admin'
    | '/authenticated'
    | '/country/$countryId'
    | '/options/index-option-1'
    | '/options/index-option-1b'
    | '/options/index-option-2'
    | '/options/index-option-3'
    | '/options/index-option-4'
    | '/options/index-option-5'
    | '/options/index-option-5b'
    | '/options/index-option-6'
    | '/options/index-original'
    | '/admin/colours'
    | '/admin/countries'
    | '/admin/featured'
    | '/admin/'
    | '/admin/country/$countryId'
    | '/country/$countryId/city/$cityId'
    | '/admin/country/$countryId/'
    | '/admin/country/$countryId/city/$cityId'
    | '/admin/country/$countryId/city/$cityId/'
    | '/admin/country/$countryId/city/$cityId/place/$placeId'
    | '/admin/country/$countryId/city/$cityId/place/$placeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/country/$countryId'
    | '/options/index-option-1'
    | '/options/index-option-1b'
    | '/options/index-option-2'
    | '/options/index-option-3'
    | '/options/index-option-4'
    | '/options/index-option-5'
    | '/options/index-option-5b'
    | '/options/index-option-6'
    | '/options/index-original'
    | '/admin/colours'
    | '/admin/countries'
    | '/admin/featured'
    | '/admin'
    | '/country/$countryId/city/$cityId'
    | '/admin/country/$countryId'
    | '/admin/country/$countryId/city/$cityId'
    | '/admin/country/$countryId/city/$cityId/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/admin'
    | '/_authenticated/authenticated'
    | '/country/$countryId'
    | '/options/index-option-1'
    | '/options/index-option-1b'
    | '/options/index-option-2'
    | '/options/index-option-3'
    | '/options/index-option-4'
    | '/options/index-option-5'
    | '/options/index-option-5b'
    | '/options/index-option-6'
    | '/options/index-original'
    | '/_authenticated/admin/colours'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/featured'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/country/$countryId'
    | '/country/$countryId/city/$cityId'
    | '/_authenticated/admin/country/$countryId/'
    | '/_authenticated/admin/country/$countryId/city/$cityId'
    | '/_authenticated/admin/country/$countryId/city/$cityId/'
    | '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId'
    | '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  CountryCountryIdRoute: typeof CountryCountryIdRouteWithChildren
  OptionsIndexOption1Route: typeof OptionsIndexOption1Route
  OptionsIndexOption1bRoute: typeof OptionsIndexOption1bRoute
  OptionsIndexOption2Route: typeof OptionsIndexOption2Route
  OptionsIndexOption3Route: typeof OptionsIndexOption3Route
  OptionsIndexOption4Route: typeof OptionsIndexOption4Route
  OptionsIndexOption5Route: typeof OptionsIndexOption5Route
  OptionsIndexOption5bRoute: typeof OptionsIndexOption5bRoute
  OptionsIndexOption6Route: typeof OptionsIndexOption6Route
  OptionsIndexOriginalRoute: typeof OptionsIndexOriginalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-original': {
      id: '/options/index-original'
      path: '/options/index-original'
      fullPath: '/options/index-original'
      preLoaderRoute: typeof OptionsIndexOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-6': {
      id: '/options/index-option-6'
      path: '/options/index-option-6'
      fullPath: '/options/index-option-6'
      preLoaderRoute: typeof OptionsIndexOption6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-5b': {
      id: '/options/index-option-5b'
      path: '/options/index-option-5b'
      fullPath: '/options/index-option-5b'
      preLoaderRoute: typeof OptionsIndexOption5bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-5': {
      id: '/options/index-option-5'
      path: '/options/index-option-5'
      fullPath: '/options/index-option-5'
      preLoaderRoute: typeof OptionsIndexOption5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-4': {
      id: '/options/index-option-4'
      path: '/options/index-option-4'
      fullPath: '/options/index-option-4'
      preLoaderRoute: typeof OptionsIndexOption4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-3': {
      id: '/options/index-option-3'
      path: '/options/index-option-3'
      fullPath: '/options/index-option-3'
      preLoaderRoute: typeof OptionsIndexOption3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-2': {
      id: '/options/index-option-2'
      path: '/options/index-option-2'
      fullPath: '/options/index-option-2'
      preLoaderRoute: typeof OptionsIndexOption2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-1b': {
      id: '/options/index-option-1b'
      path: '/options/index-option-1b'
      fullPath: '/options/index-option-1b'
      preLoaderRoute: typeof OptionsIndexOption1bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options/index-option-1': {
      id: '/options/index-option-1'
      path: '/options/index-option-1'
      fullPath: '/options/index-option-1'
      preLoaderRoute: typeof OptionsIndexOption1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$countryId': {
      id: '/country/$countryId'
      path: '/country/$countryId'
      fullPath: '/country/$countryId'
      preLoaderRoute: typeof CountryCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/featured': {
      id: '/_authenticated/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AuthenticatedAdminFeaturedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colours': {
      id: '/_authenticated/admin/colours'
      path: '/colours'
      fullPath: '/admin/colours'
      preLoaderRoute: typeof AuthenticatedAdminColoursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/country/$countryId/city/$cityId': {
      id: '/country/$countryId/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/country/$countryId/city/$cityId'
      preLoaderRoute: typeof CountryCountryIdCityCityIdRouteImport
      parentRoute: typeof CountryCountryIdRoute
    }
    '/_authenticated/admin/country/$countryId': {
      id: '/_authenticated/admin/country/$countryId'
      path: '/country/$countryId'
      fullPath: '/admin/country/$countryId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/country/$countryId/': {
      id: '/_authenticated/admin/country/$countryId/'
      path: '/'
      fullPath: '/admin/country/$countryId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/admin/country/$countryId/city/$cityId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/'
      path: '/'
      fullPath: '/admin/country/$countryId/city/$cityId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/admin/country/$countryId/city/$cityId/place/$placeId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/'
      path: '/'
      fullPath: '/admin/country/$countryId/city/$cityId/place/$placeId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute
    }
  }
}

interface AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren {
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}

const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren: AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute,
  }

const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren,
  )

interface AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren {
  AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
}

const AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren: AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute,
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren,
  }

const AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdCityCityIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren,
  )

interface AuthenticatedAdminCountryCountryIdRouteChildren {
  AuthenticatedAdminCountryCountryIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdIndexRoute
  AuthenticatedAdminCountryCountryIdCityCityIdRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
}

const AuthenticatedAdminCountryCountryIdRouteChildren: AuthenticatedAdminCountryCountryIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdIndexRoute:
      AuthenticatedAdminCountryCountryIdIndexRoute,
    AuthenticatedAdminCountryCountryIdCityCityIdRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren,
  }

const AuthenticatedAdminCountryCountryIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminColoursRoute: typeof AuthenticatedAdminColoursRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminFeaturedRoute: typeof AuthenticatedAdminFeaturedRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCountryCountryIdRoute: typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminColoursRoute: AuthenticatedAdminColoursRoute,
  AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
  AuthenticatedAdminFeaturedRoute: AuthenticatedAdminFeaturedRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCountryCountryIdRoute:
    AuthenticatedAdminCountryCountryIdRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CountryCountryIdRouteChildren {
  CountryCountryIdCityCityIdRoute: typeof CountryCountryIdCityCityIdRoute
}

const CountryCountryIdRouteChildren: CountryCountryIdRouteChildren = {
  CountryCountryIdCityCityIdRoute: CountryCountryIdCityCityIdRoute,
}

const CountryCountryIdRouteWithChildren =
  CountryCountryIdRoute._addFileChildren(CountryCountryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  CountryCountryIdRoute: CountryCountryIdRouteWithChildren,
  OptionsIndexOption1Route: OptionsIndexOption1Route,
  OptionsIndexOption1bRoute: OptionsIndexOption1bRoute,
  OptionsIndexOption2Route: OptionsIndexOption2Route,
  OptionsIndexOption3Route: OptionsIndexOption3Route,
  OptionsIndexOption4Route: OptionsIndexOption4Route,
  OptionsIndexOption5Route: OptionsIndexOption5Route,
  OptionsIndexOption5bRoute: OptionsIndexOption5bRoute,
  OptionsIndexOption6Route: OptionsIndexOption6Route,
  OptionsIndexOriginalRoute: OptionsIndexOriginalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
