/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedAdminCountryCountryIdRouteImport } from './routes/_authenticated/admin/country.$countryId'
import { Route as AuthenticatedAdminCountryCountryIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/index'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/index'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/place.$placeId'
import { Route as AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport } from './routes/_authenticated/admin/country.$countryId/city.$cityId/place.$placeId/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCountryCountryIdRoute =
  AuthenticatedAdminCountryCountryIdRouteImport.update({
    id: '/admin/country/$countryId',
    path: '/admin/country/$countryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdIndexRoute =
  AuthenticatedAdminCountryCountryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdRouteImport.update({
    id: '/city/$cityId',
    path: '/city/$cityId',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdCityCityIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport.update({
    id: '/place/$placeId',
    path: '/place/$placeId',
    getParentRoute: () => AuthenticatedAdminCountryCountryIdCityCityIdRoute,
  } as any)
const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
  '/admin/country/$countryId/': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
  '/admin/country/$countryId/city/$cityId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
  '/admin/country/$countryId/city/$cityId/place/$placeId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/country/$countryId': typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
  '/_authenticated/admin/country/$countryId/': typeof AuthenticatedAdminCountryCountryIdIndexRoute
  '/_authenticated/admin/country/$countryId/city/$cityId': typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
  '/_authenticated/admin/country/$countryId/city/$cityId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
  '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/': typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/account'
    | '/api/auth/callback'
    | '/admin'
    | '/admin/country/$countryId'
    | '/admin/country/$countryId/'
    | '/admin/country/$countryId/city/$cityId'
    | '/admin/country/$countryId/city/$cityId/'
    | '/admin/country/$countryId/city/$cityId/place/$placeId'
    | '/admin/country/$countryId/city/$cityId/place/$placeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/account'
    | '/api/auth/callback'
    | '/admin'
    | '/admin/country/$countryId'
    | '/admin/country/$countryId/city/$cityId'
    | '/admin/country/$countryId/city/$cityId/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/account'
    | '/api/auth/callback'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/country/$countryId'
    | '/_authenticated/admin/country/$countryId/'
    | '/_authenticated/admin/country/$countryId/city/$cityId'
    | '/_authenticated/admin/country/$countryId/city/$cityId/'
    | '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId'
    | '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/country/$countryId': {
      id: '/_authenticated/admin/country/$countryId'
      path: '/admin/country/$countryId'
      fullPath: '/admin/country/$countryId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/country/$countryId/': {
      id: '/_authenticated/admin/country/$countryId/'
      path: '/'
      fullPath: '/admin/country/$countryId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/admin/country/$countryId/city/$cityId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/'
      path: '/'
      fullPath: '/admin/country/$countryId/city/$cityId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/admin/country/$countryId/city/$cityId/place/$placeId'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRoute
    }
    '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/': {
      id: '/_authenticated/admin/country/$countryId/city/$cityId/place/$placeId/'
      path: '/'
      fullPath: '/admin/country/$countryId/city/$cityId/place/$placeId/'
      preLoaderRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute
    }
  }
}

interface AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren {
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute
}

const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren: AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdIndexRoute,
  }

const AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteChildren,
  )

interface AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren {
  AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute
  AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren
}

const AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren: AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdIndexRoute,
    AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdPlacePlaceIdRouteWithChildren,
  }

const AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdCityCityIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdCityCityIdRouteChildren,
  )

interface AuthenticatedAdminCountryCountryIdRouteChildren {
  AuthenticatedAdminCountryCountryIdIndexRoute: typeof AuthenticatedAdminCountryCountryIdIndexRoute
  AuthenticatedAdminCountryCountryIdCityCityIdRoute: typeof AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren
}

const AuthenticatedAdminCountryCountryIdRouteChildren: AuthenticatedAdminCountryCountryIdRouteChildren =
  {
    AuthenticatedAdminCountryCountryIdIndexRoute:
      AuthenticatedAdminCountryCountryIdIndexRoute,
    AuthenticatedAdminCountryCountryIdCityCityIdRoute:
      AuthenticatedAdminCountryCountryIdCityCityIdRouteWithChildren,
  }

const AuthenticatedAdminCountryCountryIdRouteWithChildren =
  AuthenticatedAdminCountryCountryIdRoute._addFileChildren(
    AuthenticatedAdminCountryCountryIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCountryCountryIdRoute: typeof AuthenticatedAdminCountryCountryIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCountryCountryIdRoute:
    AuthenticatedAdminCountryCountryIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
